obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.12, -0.075], [-0.12, 0.075], [0.12, 0.09], [0.12, -0.09]]
footprint_padding: 0.1

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: hokuyo, data_type: LaserScan, topic: laser/scan, marking: true, clearing: true, obstacle_range: 4.0, raytrace_range: 3.5}
  track_unknown_space: true
  
inflater_layer:
  enabled:              true
  inflation_radius:     0.01
  cost_scaling_factor:  0.1
