TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.1
  min_vel_x: 0.1

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_theta: 1.0
  min_vel_theta: -1.0
# min_in_place_vel_theta: 1.5707
  min_in_place_rotational_vel: 0.5

  holonomic_robot: false
  escape_vel: -0.1

  acc_lim_x: 30.0
  acc_lim_y: 0.0
  acc_lim_theta: 20.0 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 8
  vtheta_samples: 20
  controller_frequency: 20.0

# Trajectory Scoring Parameters
  meter_scoring: true
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05


