map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.1

obstacles_layer:
  enabled:              true
  max_obstacle_height:  0.6
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  observation_sources: scan
  scan: {sensor_frame: hokuyo, data_type: LaserScan, topic: robot_3/laser/scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 3.0}
  track_unknown_space: true # Required for Exploration

inflater_layer:
  enabled:              true
  cost_scaling_factor:  2.5    # exponential rate at which the obstacle cost drops off (default -> 10)
  inflation_radius:     0.01   # max distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true

